# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /:categories/:year/:month/:day/:title 

# Setup
title:            Linux Tool
tagline:          'A webpage for usefully linux tool'
description:      ''
url:              http://linuxtool.net
baseurl:          /

author:
  name:           'Jingjing Shi'
  url:            https://github/shijingjing1221

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/onlinemanpage/onlinemanpage.github.io
